// <auto-generated />
using System;
using CriticalListeningLab.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CriticalListeningLab.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260911214351_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CriticalListeningLab.Api.Domain.Entities.AudioAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AudioSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("audio_source_id");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<double?>("IntegratedLufs")
                        .HasColumnType("double precision")
                        .HasColumnName("integrated_lufs");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mime_type");

                    b.Property<int>("SampleRate")
                        .HasColumnType("integer")
                        .HasColumnName("sample_rate");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.Property<string>("VariantSlug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("variant_slug");

                    b.HasKey("Id")
                        .HasName("pk_audio_assets");

                    b.HasIndex("AudioSourceId", "VariantSlug")
                        .IsUnique()
                        .HasDatabaseName("ix_audio_assets_audio_source_id_variant_slug");

                    b.ToTable("audio_assets", (string)null);
                });

            modelBuilder.Entity("CriticalListeningLab.Api.Domain.Entities.AudioSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("module_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_audio_sources");

                    b.HasIndex("ModuleId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_audio_sources_module_id_slug");

                    b.ToTable("audio_sources", (string)null);
                });

            modelBuilder.Entity("CriticalListeningLab.Api.Domain.Entities.Cohort", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_cohorts");

                    b.HasIndex("IsActive")
                        .IsUnique()
                        .HasDatabaseName("ix_cohorts_is_active")
                        .HasFilter("is_active");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_cohorts_name");

                    b.ToTable("cohorts", (string)null);
                });

            modelBuilder.Entity("CriticalListeningLab.Api.Domain.Entities.CohortModuleAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CohortId")
                        .HasColumnType("uuid")
                        .HasColumnName("cohort_id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("module_id");

                    b.HasKey("Id")
                        .HasName("pk_cohort_module_availabilities");

                    b.HasIndex("ModuleId")
                        .HasDatabaseName("ix_cohort_module_availabilities_module_id");

                    b.HasIndex("CohortId", "ModuleId")
                        .IsUnique()
                        .HasDatabaseName("ix_cohort_module_availabilities_cohort_id_module_id");

                    b.ToTable("cohort_module_availabilities", (string)null);
                });

            modelBuilder.Entity("CriticalListeningLab.Api.Domain.Entities.ExerciseLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("config_json");

                    b.Property<int>("ExerciseType")
                        .HasColumnType("integer")
                        .HasColumnName("exercise_type");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<int>("LevelNumber")
                        .HasColumnType("integer")
                        .HasColumnName("level_number");

                    b.Property<int>("PassThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("pass_threshold");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("integer")
                        .HasColumnName("question_count");

                    b.Property<Guid>("SegmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("segment_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_exercise_levels");

                    b.HasIndex("SegmentId", "LevelNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_exercise_levels_segment_id_level_number");

                    b.ToTable("exercise_levels", (string)null);
                });

            modelBuilder.Entity("CriticalListeningLab.Api.Domain.Entities.ExerciseSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("module_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_exercise_segments");

                    b.HasIndex("ModuleId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_exercise_segments_module_id_key");

                    b.ToTable("exercise_segments", (string)null);
                });

            modelBuilder.Entity("CriticalListeningLab.Api.Domain.Entities.LevelUnlockRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ExerciseLevelId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_level_id");

                    b.Property<int?>("MinScore")
                        .HasColumnType("integer")
                        .HasColumnName("min_score");

                    b.Property<Guid>("RequiredExerciseLevelId")
                        .HasColumnType("uuid")
                        .HasColumnName("required_exercise_level_id");

                    b.Property<int>("RequirementType")
                        .HasColumnType("integer")
                        .HasColumnName("requirement_type");

                    b.HasKey("Id")
                        .HasName("pk_level_unlock_requirements");

                    b.HasIndex("RequiredExerciseLevelId")
                        .HasDatabaseName("ix_level_unlock_requirements_required_exercise_level_id");

                    b.HasIndex("ExerciseLevelId", "RequiredExerciseLevelId")
                        .IsUnique()
                        .HasDatabaseName("ix_level_unlock_requirements_exercise_level_id_required_exerci");

                    b.ToTable("level_unlock_requirements", null, t =>
                        {
                            t.HasCheckConstraint("ck_level_unlock_requirement_not_self", "exercise_level_id <> required_exercise_level_id");
                        });
                });

            modelBuilder.Entity("CriticalListeningLab.Api.Domain.Entities.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsEnabledGlobally")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled_globally");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_modules");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_modules_slug");

                    b.ToTable("modules", (string)null);
                });

            modelBuilder.Entity("CriticalListeningLab.Api.Domain.Entities.StudentProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<Guid>("AudioSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("audio_source_id");

                    b.Property<int>("BestScore")
                        .HasColumnType("integer")
                        .HasColumnName("best_score");

                    b.Property<Guid>("ExerciseLevelId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_level_id");

                    b.Property<DateTimeOffset?>("FirstPassedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_passed_at");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_passed");

                    b.Property<DateTimeOffset>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_student_progress");

                    b.HasIndex("AudioSourceId")
                        .HasDatabaseName("ix_student_progress_audio_source_id");

                    b.HasIndex("ExerciseLevelId")
                        .HasDatabaseName("ix_student_progress_exercise_level_id");

                    b.HasIndex("UserId", "AudioSourceId")
                        .HasDatabaseName("ix_student_progress_user_id_audio_source_id");

                    b.HasIndex("UserId", "AudioSourceId", "ExerciseLevelId")
                        .IsUnique()
                        .HasDatabaseName("ix_student_progress_user_id_audio_source_id_exercise_level_id");

                    b.ToTable("student_progress", (string)null);
                });

            modelBuilder.Entity("CriticalListeningLab.Api.Domain.Entities.TestSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AudioSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("audio_source_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("integer")
                        .HasColumnName("correct_answers");

                    b.Property<Guid>("ExerciseLevelId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_level_id");

                    b.Property<int>("PassThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("pass_threshold");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean")
                        .HasColumnName("passed");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("integer")
                        .HasColumnName("question_count");

                    b.Property<int>("RandomSeed")
                        .HasColumnType("integer")
                        .HasColumnName("random_seed");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_test_sessions");

                    b.HasIndex("AudioSourceId")
                        .HasDatabaseName("ix_test_sessions_audio_source_id");

                    b.HasIndex("ExerciseLevelId")
                        .HasDatabaseName("ix_test_sessions_exercise_level_id");

                    b.HasIndex("UserId", "ExerciseLevelId", "AudioSourceId", "Status")
                        .HasDatabaseName("ix_test_sessions_user_id_exercise_level_id_audio_source_id_sta");

                    b.ToTable("test_sessions", (string)null);
                });

            modelBuilder.Entity("CriticalListeningLab.Api.Domain.Entities.TestSessionQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<Guid?>("AudioAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("audio_asset_id");

                    b.Property<Guid>("AudioToken")
                        .HasColumnType("uuid")
                        .HasColumnName("audio_token");

                    b.Property<string>("CorrectAnswerKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correct_answer_key");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<string>("PromptJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("prompt_json");

                    b.Property<int>("QuestionIndex")
                        .HasColumnType("integer")
                        .HasColumnName("question_index");

                    b.Property<string>("StudentAnswerKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("student_answer_key");

                    b.Property<Guid>("TestSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_session_id");

                    b.HasKey("Id")
                        .HasName("pk_test_session_questions");

                    b.HasIndex("AudioAssetId")
                        .HasDatabaseName("ix_test_session_questions_audio_asset_id");

                    b.HasIndex("AudioToken")
                        .IsUnique()
                        .HasDatabaseName("ix_test_session_questions_audio_token");

                    b.HasIndex("TestSessionId", "QuestionIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_test_session_questions_test_session_id_question_index");

                    b.ToTable("test_session_questions", (string)null);
                });

            modelBuilder.Entity("CriticalListeningLab.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CohortId")
                        .HasColumnType("uuid")
                        .HasColumnName("cohort_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("EntraObjectId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entra_object_id");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CohortId")
                        .HasDatabaseName("ix_users_cohort_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("EntraObjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_entra_object_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CriticalListeningLab.Api.Domain.Entities.AudioAsset", b =>
                {
                    b.HasOne("CriticalListeningLab.Api.Domain.Entities.AudioSource", "AudioSource")
                        .WithMany("Assets")
                        .HasForeignKey("AudioSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audio_assets_audio_sources_audio_source_id");

                    b.Navigation("AudioSource");
                });

            modelBuilder.Entity("CriticalListeningLab.Api.Domain.Entities.AudioSource", b =>
                {
                    b.HasOne("CriticalListeningLab.Api.Domain.Entities.Module", "Module")
                        .WithMany("AudioSources")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audio_sources_modules_module_id");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("CriticalListeningLab.Api.Domain.Entities.CohortModuleAvailability", b =>
                {
                    b.HasOne("CriticalListeningLab.Api.Domain.Entities.Cohort", "Cohort")
                        .WithMany("ModuleAvailabilities")
                        .HasForeignKey("CohortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cohort_module_availabilities_cohorts_cohort_id");

                    b.HasOne("CriticalListeningLab.Api.Domain.Entities.Module", "Module")
                        .WithMany("CohortAvailabilities")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cohort_module_availabilities_modules_module_id");

                    b.Navigation("Cohort");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("CriticalListeningLab.Api.Domain.Entities.ExerciseLevel", b =>
                {
                    b.HasOne("CriticalListeningLab.Api.Domain.Entities.ExerciseSegment", "Segment")
                        .WithMany("Levels")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exercise_levels_exercise_segments_segment_id");

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("CriticalListeningLab.Api.Domain.Entities.ExerciseSegment", b =>
                {
                    b.HasOne("CriticalListeningLab.Api.Domain.Entities.Module", "Module")
                        .WithMany("Segments")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_exercise_segments_modules_module_id");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("CriticalListeningLab.Api.Domain.Entities.LevelUnlockRequirement", b =>
                {
                    b.HasOne("CriticalListeningLab.Api.Domain.Entities.ExerciseLevel", "ExerciseLevel")
                        .WithMany("UnlockRequirements")
                        .HasForeignKey("ExerciseLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_level_unlock_requirements_exercise_levels_exercise_level_id");

                    b.HasOne("CriticalListeningLab.Api.Domain.Entities.ExerciseLevel", "RequiredExerciseLevel")
                        .WithMany("UnlocksRequirements")
                        .HasForeignKey("RequiredExerciseLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_level_unlock_requirements_exercise_levels_required_exercise");

                    b.Navigation("ExerciseLevel");

                    b.Navigation("RequiredExerciseLevel");
                });

            modelBuilder.Entity("CriticalListeningLab.Api.Domain.Entities.StudentProgress", b =>
                {
                    b.HasOne("CriticalListeningLab.Api.Domain.Entities.AudioSource", "AudioSource")
                        .WithMany("Progress")
                        .HasForeignKey("AudioSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_student_progress_audio_sources_audio_source_id");

                    b.HasOne("CriticalListeningLab.Api.Domain.Entities.ExerciseLevel", "ExerciseLevel")
                        .WithMany("Progress")
                        .HasForeignKey("ExerciseLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_student_progress_exercise_levels_exercise_level_id");

                    b.HasOne("CriticalListeningLab.Api.Domain.Entities.User", "User")
                        .WithMany("Progress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_progress_users_user_id");

                    b.Navigation("AudioSource");

                    b.Navigation("ExerciseLevel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CriticalListeningLab.Api.Domain.Entities.TestSession", b =>
                {
                    b.HasOne("CriticalListeningLab.Api.Domain.Entities.AudioSource", "AudioSource")
                        .WithMany("TestSessions")
                        .HasForeignKey("AudioSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_test_sessions_audio_sources_audio_source_id");

                    b.HasOne("CriticalListeningLab.Api.Domain.Entities.ExerciseLevel", "ExerciseLevel")
                        .WithMany("TestSessions")
                        .HasForeignKey("ExerciseLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_test_sessions_exercise_levels_exercise_level_id");

                    b.HasOne("CriticalListeningLab.Api.Domain.Entities.User", "User")
                        .WithMany("TestSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_sessions_users_user_id");

                    b.Navigation("AudioSource");

                    b.Navigation("ExerciseLevel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CriticalListeningLab.Api.Domain.Entities.TestSessionQuestion", b =>
                {
                    b.HasOne("CriticalListeningLab.Api.Domain.Entities.AudioAsset", "AudioAsset")
                        .WithMany()
                        .HasForeignKey("AudioAssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_test_session_questions_audio_assets_audio_asset_id");

                    b.HasOne("CriticalListeningLab.Api.Domain.Entities.TestSession", "TestSession")
                        .WithMany("Questions")
                        .HasForeignKey("TestSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_session_questions_test_sessions_test_session_id");

                    b.Navigation("AudioAsset");

                    b.Navigation("TestSession");
                });

            modelBuilder.Entity("CriticalListeningLab.Api.Domain.Entities.User", b =>
                {
                    b.HasOne("CriticalListeningLab.Api.Domain.Entities.Cohort", "Cohort")
                        .WithMany("Users")
                        .HasForeignKey("CohortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_cohorts_cohort_id");

                    b.Navigation("Cohort");
                });

            modelBuilder.Entity("CriticalListeningLab.Api.Domain.Entities.AudioSource", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Progress");

                    b.Navigation("TestSessions");
                });

            modelBuilder.Entity("CriticalListeningLab.Api.Domain.Entities.Cohort", b =>
                {
                    b.Navigation("ModuleAvailabilities");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CriticalListeningLab.Api.Domain.Entities.ExerciseLevel", b =>
                {
                    b.Navigation("Progress");

                    b.Navigation("TestSessions");

                    b.Navigation("UnlockRequirements");

                    b.Navigation("UnlocksRequirements");
                });

            modelBuilder.Entity("CriticalListeningLab.Api.Domain.Entities.ExerciseSegment", b =>
                {
                    b.Navigation("Levels");
                });

            modelBuilder.Entity("CriticalListeningLab.Api.Domain.Entities.Module", b =>
                {
                    b.Navigation("AudioSources");

                    b.Navigation("CohortAvailabilities");

                    b.Navigation("Segments");
                });

            modelBuilder.Entity("CriticalListeningLab.Api.Domain.Entities.TestSession", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("CriticalListeningLab.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("Progress");

                    b.Navigation("TestSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
