export const strings = {
  appName: "Critical Listening Lab",
  appTagline: "Trening kritičkog slušanja",
  loginTitle: "Prijava",
  loginBody:
    "Prijavi se Algebra računom. Aplikacija ne čuva lozinke — identitet dolazi iz Entra ID-a.",
  loginAction: "Prijava Algebra računom",
  loginDevAction: "Uđi u laboratorij",
  loginDevNote: "Razvojni način: Entra prijava je preskočena.",
  logout: "Odjava",
  dashboard: "Moduli",
  back: "Natrag",
  unavailable: "Nije dostupno",
  unavailableGlobally: "Modul je trenutno isključen.",
  unavailableCohort: "Modul nije uključen za tvoj cohort.",
  sources: "Audio izvori",
  levels: "Leveli",
  completed: "Završeno",
  practice: "Vježba",
  practiceSoon: "Vježba za kompresiju dolazi u sljedećoj fazi.",
  practiceHint:
    "Odaberi frekvenciju i pojačanje, zatim pokreni slušanje. Vidiš što slušaš — ovo ne ulazi u napredak i ne otključava razine.",
  play: "Slušaj",
  stop: "Stani",
  volume: "Glasnoća",
  source: "Izvorno",
  processed: "Procesirano",
  listenShortcuts: "Tab prebacuje izvorno / procesirano · Space pokreće i zaustavlja.",
  clickToHear: "Pokreni slušanje kad si spreman. Space pokreće i zaustavlja.",
  startTest: "Pokreni test",
  retryTest: "Ponovi test",
  continueTest: "Nastavi",
  openLevel: "Poslušaj",
  previewHint:
    "Odaberi pojas, zatim pokreni slušanje. Glasnoću podešavaš sam. Kad si spreman, pokreni test.",
  previewHintCompression:
    "Odaberi opciju, zatim pokreni slušanje. Glasnoću podešavaš sam. Kad si spreman, pokreni test.",
  listenBand: "Slušaš",
  flat: "ravni signal",
  audioDecodeFailed:
    "Ovaj preglednik ne može dekodirati audio, ili fajl još nije na serveru. Test možeš svejedno pokrenuti.",
  boost: "Pojačanje",
  cut: "Smanjenje",
  abandon: "Odustani",
  abandonConfirm: "Odustati od testa? Ovaj pokušaj se ne boduje.",
  question: "Pitanje",
  next: "Sljedeće pitanje",
  seeResult: "Pogledaj rezultat",
  eqMove: "EQ potez",
  correct: "Točno",
  incorrect: "Netočno",
  passed: "Prolaz",
  failed: "Pad",
  score: "Rezultat",
  firstPass: "Prvi prolaz ovog levela.",
  unlocked: "Novootključano",
  backToTree: "Natrag na stablo",
  introTitle: "Upoznavanje s frekvencijama",
  introStart: "Započni upoznavanje",
  introContinue: "Nastavi upoznavanje",
  introLead:
    "Prije Razina 1 poslušaj osnovne frekvencije i riješi kratke mini-testove. Mini-testovi nemaju prag prolaza.",
  introLeadB: "Razina 1 je položena. Upoznaj 250 Hz, 1 kHz i 4 kHz, zatim riješi kratki mini-test.",
  introMeetA1: "Upoznaj osnovne niske frekvencije",
  introMeetA2: "Upoznaj osnovne visoke frekvencije",
  introMeetB: "Upoznaj međufrekvencije",
  introGotIt: "Idem dalje",
  introStartQuiz: "Kreni na mini-test",
  introCompareHint: "Prebaci Izvorno / Procesirano da čuješ tu frekvenciju.",
  introQuizDone: "Mini-test je završen",
  introQuizDoneHint: "Rezultat se ne boduje za prolaz — nastavi dalje kroz upoznavanje.",
  introPhaseADone: "Osnovne frekvencije su upoznate",
  introPhaseADoneHint: "Razina 1 je otključana. Položi je s barem 80 % točnosti da otvoriš sljedeći skup.",
  introDone: "Upoznavanje je završeno",
  introDoneHint: "Sve predviđene frekvencije su predstavljene. Možeš se vratiti na stablo razina.",
  goToLevel1: "Idi na Razinu 1",
  continueIntro: "Nastavi upoznavanje",
  audioSoon: "Slušanje se uključuje u sljedećoj fazi. Odgovori i napredak već rade.",
  loading: "Učitavanje…",
  error: "Nešto nije u redu.",
  retry: "Pokušaj ponovo",
  lockedLevel: "Level još nije otključan.",
  attempt: "pokušaj",
  attempts: "pokušaja",
  bestAttempt: "Najbolji pokušaj",
  passFrom: "prolaz od",
  statusLocked: "Zaključano",
  statusUnlocked: "Otključano",
  statusInProgress: "U tijeku",
  statusCompleted: "Završeno",
  adminSoon: "Admin",
  of: "od"
} as const;
