export const strings = {
  appName: "Trening kritičkog slušanja",
  loginTitle: "Prijava",
  loginBody:
    "Prijavi se Algebra računom. Aplikacija ne čuva lozinke — identitet dolazi iz Entra ID-a.",
  loginAction: "Prijava Algebra računom",
  loginDevAction: "Uđi u laboratorij",
  loginDevNote: "Razvojni način: Entra prijava je preskočena.",
  logout: "Odjava",
  dashboard: "Moduli",
  back: "Natrag",
  unavailable: "Nije dostupno",
  unavailableGlobally: "Modul je trenutno isključen.",
  unavailableCohort: "Modul nije uključen za tvoj cohort.",
  sources: "Audio izvori",
  sourceLocked: "Zaključano",
  sourceLockedHint: "Dostupno nakon upoznavanja s frekvencijama na ružičastom šumu.",
  levels: "Razine",
  completed: "Savladano",
  practice: "Trening mod",
  practiceSoon: "Izazov za kompresiju dolazi u sljedećoj fazi.",
  practiceHint:
    "Odaberi željenu frekvenciju i pojačanje pa usporedi izvorni i promijenjeni zvuk. Trening mod služi isključivo za građenje slušne memorije i zagrijavanje uha. Ne ulazi u statistiku napretka i ne otključava nove razine.",
  play: "Slušaj",
  stop: "Stani",
  volume: "Glasnoća",
  source: "Izvorno",
  processed: "Procesirano",
  listenShortcuts: "Tab prebacuje izvorno / procesirano · Space pokreće i zaustavlja.",
  clickToHear: "Pokreni slušanje kad si spreman. Space pokreće i zaustavlja.",
  startTest: "Pokreni izazov",
  retryTest: "Ponovi izazov",
  continueTest: "Nastavi",
  openLevel: "Otvori",
  previewHint:
    "Odaberi pojas, zatim pokreni slušanje. Glasnoću podešavaš sam. Kad si spreman, pokreni izazov.",
  previewHintCompression:
    "Odaberi opciju, zatim pokreni slušanje. Glasnoću podešavaš sam. Kad si spreman, pokreni izazov.",
  listenBand: "Slušaš",
  flat: "ravni signal",
  audioDecodeFailed:
    "Ovaj preglednik ne može dekodirati audio, ili fajl još nije na serveru. Izazov možeš svejedno pokrenuti.",
  boost: "Pojačanje",
  cut: "Smanjenje",
  abandon: "Odustani",
  abandonConfirm: "Odustani od izazova? Ovaj pokušaj ne ulazi u ukupan rezultat.",
  question: "Pitanje",
  next: "Sljedeće pitanje",
  finishTest: "Završi izazov",
  seeResult: "Pogledaj rezultat",
  eqMove: "EQ potez",
  correct: "Točno",
  incorrect: "Netočno",
  passed: "Prolaz",
  failed: "Pad",
  score: "Rezultat",
  firstPass: "Prvi prolaz ove razine.",
  unlocked: "Novootključano",
  backToTree: "Natrag na izazove",
  introTitle: "Upoznavanje s frekvencijama",
  introStart: "Započni upoznavanje",
  introContinue: "Nastavi upoznavanje",
  introLead:
    "Prije rješavanja individualnih razina, poslušaj osnovne frekvencije i riješi kratke mini-izazove.",
  introLeadB: "Razina 1 je položena. Upoznaj 250 Hz, 1 kHz i 4 kHz, zatim riješi kratki mini-izazov.",
  introMeetA1: "Upoznaj osnovne niske frekvencije",
  introMeetA2: "Upoznaj osnovne visoke frekvencije",
  introMeetB: "Upoznaj međufrekvencije",
  introGotIt: "Idem dalje",
  introStartQuiz: "Kreni na mini-izazov",
  introCompareHint: "Prebaci Izvorno / Procesirano da čuješ tu frekvenciju.",
  introQuizDone: "Mini-izazov je završen",
  introQuizDoneHint: "Rezultat se ne boduje za prolaz — nastavi dalje kroz upoznavanje.",
  introQuizDoneHintA2: "Rezultat se ne boduje za prolaz — nastavi na prvu razinu.",
  introQuizDoneHintB: "Rezultat se ne boduje za prolaz — nastavi s izazovima.",
  continueTests: "Nastavi s izazovima",
  continueToLevel1: "Nastavi na Boost +12 dB",
  continueFrequencyIntro: "Nastavi s upoznavanjem frekvencija",
  introPhaseADone: "Osnovne frekvencije su upoznate",
  introPhaseADoneHint: "Razina 1 je otključana. Položi je s barem 80 % točnosti da otvoriš sljedeći skup.",
  introDone: "Upoznavanje je završeno",
  introDoneHint: "Sve predviđene frekvencije su predstavljene. Možeš se vratiti na stablo razina.",
  goToLevel1: "Idi na Razinu 1",
  continueIntro: "Nastavi upoznavanje",
  audioSoon: "Slušanje se uključuje u sljedećoj fazi. Odgovori i napredak već rade.",
  loading: "Učitavanje…",
  error: "Nešto nije u redu.",
  retry: "Pokušaj ponovo",
  lockedLevel: "Razina još nije otključana.",
  attempt: "pokušaj",
  attempts: "Broj pokušaja",
  bestAttempt: "Najbolji pokušaj",
  passFrom: "za prolaz treba",
  statusLocked: "Zaključano",
  statusUnlocked: "Otključano",
  statusInProgress: "U tijeku",
  statusCompleted: "Savladano",
  adminSoon: "Admin",
  of: "od"
} as const;
